SELECT
  STATUS,
  CASE
    WHEN SERVICE_START_DATE = '9999-09-09' THEN 'ACTIVE'
    WHEN SERVICE_START_DATE <= DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE MORE 60 DAYS'
    WHEN SERVICE_START_DATE > DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE WITH 60 DAYS'
END
  SERVICE_START_DATE_FLAG,
  CASE
    WHEN SERVICE_CEASE_DATE = '9999-09-09' THEN 'ACTIVE'
    WHEN SERVICE_CEASE_DATE <= DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'CEASED MORE 60 DAYS'
    WHEN SERVICE_CEASE_DATE > DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'CEASED WITH 60 DAYS'
END
  CEASE_FLAG,
  CASE
    WHEN LAST_BILL_DATE IS NULL THEN 'not billed'
  ELSE
  'yes billed'
END
  billed_flag,
  ORDER_STATUS_CODE,
  ORDER_TYPE_CODE,
  CASE
    WHEN STATUS_DATE = '9999-09-09' THEN 'ACTIVE'
    WHEN STATUS_DATE <= DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE MORE 60 DAYS'
    WHEN STATUS_DATE > DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE WITH 60 DAYS'
END
  CRM_STATUS_DATE,
  CASE
    WHEN FIRST_ACTIVATION_DATE = '9999-09-09' THEN 'ACTIVE'
    WHEN FIRST_ACTIVATION_DATE <= DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE MORE 60 DAYS'
    WHEN FIRST_ACTIVATION_DATE > DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH), INTERVAL 2 month) THEN 'ACTIVE WITH 60 DAYS'
END
  CRM_FIRST_DATE,
  CASE
    WHEN ACCOUNT_NUMBER IS NULL THEN 'NO ACCOUNT NUMBER'
  ELSE
  'YES ACCOUNT NUMBER'
END
  ACCOUNT_FLAG,
  COUNT(DISTINCT( Reference_CLI)) AS CUSTOMER,
  SUM(INVOICE_VALUE) AS BILLED_VALUE
FROM
  `skyuk-uk-csgbillanalysis-dev.roi_rental.roi_*`
WHERE
  _TABLE_SUFFIX = CONCAT(LOWER(FORMAT_DATE('%b_%y', CURRENT_DATE())), '_talk_rentals')
GROUP BY
  STATUS,
  CEASE_FLAG,
  ORDER_STATUS_CODE,
  ORDER_TYPE_CODE,
  billed_flag,
  CRM_STATUS_DATE,
  CRM_FIRST_DATE,
  ACCOUNT_FLAG,
  SERVICE_START_DATE_FLAG